# Generated by Django 4.2.7 on 2026-01-06 11:34

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About KUAI Club', max_length=200)),
                ('content', models.TextField(help_text='Hero section description')),
                ('hero_stat_1_value', models.CharField(default='500+', max_length=20)),
                ('hero_stat_1_label', models.CharField(default='Students', max_length=50)),
                ('hero_stat_2_value', models.CharField(default='50+', max_length=20)),
                ('hero_stat_2_label', models.CharField(default='Projects', max_length=50)),
                ('hero_stat_3_value', models.CharField(default='15+', max_length=20)),
                ('hero_stat_3_label', models.CharField(default='Partners', max_length=50)),
                ('hero_stat_4_value', models.CharField(default='3', max_length=20)),
                ('hero_stat_4_label', models.CharField(default='Years', max_length=50)),
                ('who_we_are_title', models.CharField(default='Who We Are', max_length=200)),
                ('who_we_are_description', models.TextField()),
                ('who_we_are_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='about/')),
                ('why_exist_title', models.CharField(default='Why We Exist', max_length=200)),
                ('why_exist_description', models.TextField()),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='about/', verbose_name='Why We Exist Image')),
                ('mission', models.TextField(verbose_name='Our Mission')),
                ('vision', models.TextField(verbose_name='Our Vision')),
                ('impact_subtitle', models.CharField(blank=True, max_length=500)),
                ('impact_stat_1_value', models.CharField(default='1000+', max_length=20)),
                ('impact_stat_1_label', models.CharField(default='Students Empowered', max_length=100)),
                ('impact_stat_2_value', models.CharField(default='75+', max_length=20)),
                ('impact_stat_2_label', models.CharField(default='AI Projects Completed', max_length=100)),
                ('impact_stat_3_value', models.CharField(default='25+', max_length=20)),
                ('impact_stat_3_label', models.CharField(default='Partner Organizations', max_length=100)),
                ('impact_stat_4_value', models.CharField(default='5', max_length=20)),
                ('impact_stat_4_label', models.CharField(default='Years of Innovation', max_length=100)),
                ('cta_title', models.CharField(default='Ready to Join the AI Revolution?', max_length=200)),
                ('cta_description', models.TextField()),
                ('cta_primary_text', models.CharField(default='Get Started Today', max_length=50)),
                ('cta_primary_link', models.CharField(default='/', max_length=200)),
                ('cta_secondary_text', models.CharField(default='Explore Programs', max_length=50)),
                ('cta_secondary_link', models.CharField(default='/#projects-section', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
    ]
