# Generated by Django 4.2.7 on 2026-01-06 11:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category_type', models.CharField(choices=[('platinum', 'Platinum Partner'), ('gold', 'Gold Partner'), ('silver', 'Silver Partner'), ('academic', 'Academic Partner'), ('technology', 'Technology Partner'), ('community', 'Community Partner')], default='community', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner Category',
                'verbose_name_plural': 'Partner Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('logo', imagekit.models.fields.ProcessedImageField(help_text='Partner logo (transparent PNG recommended)', upload_to='partners/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])])),
                ('website_url', models.URLField(blank=True, verbose_name='Website URL')),
                ('partnership_level', models.CharField(blank=True, help_text='e.g., Gold Sponsor, Strategic Partner', max_length=50)),
                ('partnership_since', models.DateField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower first)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Partner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='partners.partnercategory')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['order', 'name'],
            },
        ),
    ]
