# Generated by Django 4.2.7 on 2026-01-06 11:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Role',
                'verbose_name_plural': 'Team Roles',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, help_text='Custom title/position (overrides role if provided)', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Brief biography')),
                ('photo', imagekit.models.fields.ProcessedImageField(help_text='Recommended: Square image (400x400px)', upload_to='team/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn Profile')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X Profile')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub Profile')),
                ('website_url', models.URLField(blank=True, verbose_name='Personal Website')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower first)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('is_executive', models.BooleanField(default=False, verbose_name='Executive Team Member')),
                ('joined_date', models.DateField(blank=True, help_text='Date joined KUAI', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='team.teamrole')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
