# Generated by Django 6.0 on 2026-01-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='role',
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['-start_year', '-end_year', 'order', 'name'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AddField(
            model_name='teammember',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, help_text='Leadership end year; if blank, member is current', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='start_year',
            field=models.PositiveIntegerField(default=2026, help_text='Leadership start year (e.g. 2024)'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='joined_date',
            field=models.DateField(blank=True, help_text='Date joined KUAI or club', null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='title',
            field=models.CharField(blank=True, help_text='Custom title/position (e.g. President, Secretary)', max_length=200),
        ),
        migrations.DeleteModel(
            name='TeamRole',
        ),
    ]
