# Generated by Django 4.2.7 on 2026-01-06 10:25

import django.core.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Primary contact email', max_length=254)),
                ('phone', models.CharField(help_text='Phone number with country code (e.g., +256)', max_length=20)),
                ('address', models.TextField(help_text='Physical address')),
                ('office_hours', models.CharField(blank=True, help_text='e.g., Mon-Fri:  9AM-5PM', max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate for map', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate for map', max_digits=9, null=True)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact number', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(help_text='Recommended size: 1920x1080px', upload_to='hero/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])])),
                ('image_alt', models.CharField(blank=True, help_text='Describe the image for accessibility', max_length=200)),
                ('button1_text', models.CharField(blank=True, max_length=50)),
                ('button1_url', models.CharField(blank=True, max_length=200)),
                ('button1_style', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark')], default='primary', max_length=50)),
                ('button2_text', models.CharField(blank=True, max_length=50)),
                ('button2_url', models.CharField(blank=True, max_length=200)),
                ('button2_style', models.CharField(choices=[('outline-primary', 'Outline Primary'), ('outline-secondary', 'Outline Secondary'), ('outline-light', 'Outline Light'), ('outline-dark', 'Outline Dark')], default='outline-light', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this slide')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('open_new_tab', models.BooleanField(default=True, help_text='Open link in new tab')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quick Link',
                'verbose_name_plural': 'Quick Links',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='KUAI Club', max_length=200)),
                ('site_tagline', models.CharField(blank=True, max_length=500)),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Logo will be resized to fit 300x100px', null=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])])),
                ('favicon', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Favicon will be resized to 32x32px', null=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(['png', 'ico'])])),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='WhatsApp URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('meta_description', models.TextField(blank=True, help_text='Max 160 characters for SEO', max_length=160)),
                ('meta_keywords', models.TextField(blank=True, help_text='Comma-separated keywords')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
