# Generated by Django 4.2.7 on 2026-01-06 11:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndabaxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('theme', models.CharField(blank=True, help_text='Event theme', max_length=200)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='indabax/events/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])])),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('registration_url', models.URLField(blank=True)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Indabax Event',
                'verbose_name_plural': 'Indabax Events',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='IndabaxSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Indabax Kabale', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='indabax/logos/')),
                ('about_title', models.CharField(default='About Indabax Kabale', max_length=200)),
                ('about_description', models.TextField()),
                ('about_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='indabax/about/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Indabax Settings',
                'verbose_name_plural': 'Indabax Settings',
            },
        ),
        migrations.CreateModel(
            name='IndabaxSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(help_text='Professional title/position', max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField()),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='indabax/speakers/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_keynote', models.BooleanField(default=False, verbose_name='Keynote Speaker')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='indabax.indabaxevent')),
            ],
            options={
                'verbose_name': 'Indabax Speaker',
                'verbose_name_plural': 'Indabax Speakers',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IndabaxSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('session_type', models.CharField(choices=[('keynote', 'Keynote'), ('talk', 'Talk'), ('workshop', 'Workshop'), ('panel', 'Panel Discussion'), ('tutorial', 'Tutorial')], default='talk', max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=100)),
                ('slides_url', models.URLField(blank=True, verbose_name='Slides URL')),
                ('video_url', models.URLField(blank=True, verbose_name='Recording URL')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='indabax.indabaxevent')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='indabax.indabaxspeaker')),
            ],
            options={
                'verbose_name': 'Indabax Session',
                'verbose_name_plural': 'Indabax Sessions',
                'ordering': ['date', 'start_time', 'order'],
            },
        ),
        migrations.CreateModel(
            name='IndabaxGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='indabax/gallery/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])])),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('date_taken', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to='indabax.indabaxevent')),
            ],
            options={
                'verbose_name': 'Indabax Gallery Image',
                'verbose_name_plural': 'Indabax Gallery Images',
                'ordering': ['order', '-date_taken'],
            },
        ),
    ]
