# Generated by Django 6.0 on 2026-01-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indabax', '0006_alter_learningresource_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leader',
            options={'ordering': ['-start_year', '-end_year', 'name'], 'verbose_name': 'Leader', 'verbose_name_plural': 'Leaders'},
        ),
        migrations.RemoveField(
            model_name='leader',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='year',
        ),
        migrations.AddField(
            model_name='leader',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, help_text='Leadership end year; blank = current', null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='start_year',
            field=models.PositiveIntegerField(default=2026, help_text='Leadership start year'),
        ),
    ]
